language: node_js

node_js:
  - 6.10.2

branches:
  only:
    - master

cache:
  directories:
  - node_modules

install:
  - npm i -g @angular/cli@1.0.0

script:
  - ng lint
  - ng test
  - ng e2e


#Deploy
# ng build --prod --base-href "https://notsaltydev.github.io/todo-app/" ngh
# angular-cli-ghpages
