
language: node_js

node_js:
  - 6.10.2

cache:
  directories:
  - node_modules

install:
  - npm i --silent --no-optional -g @angular/cli@1.0.0
  - npm i --silent --no-optional -g angular-cli-ghpages

script:
  - ng build --prod --base-href "https://notsaltydev.github.io/todo-app/" ngh
  - angular-cli-ghpages


#only building specific branches
branches:
  only:
    - master
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
