
language: node_js

node_js:
  - 6.10.2


branches:
  only:
    - master

cache:
  directories:
  - node_modules

install:
  - npm i --silent --no-optional -g @angular/cli@1.0.0
  - npm i --silent --no-optional -g angular-cli-ghpages

script:
  - ng build --prod --base-href "https://notsaltydev.github.io/todo-app/" ngh


