#.travis.yml

language: node_js
node_js:
  - "6.10.2"

branches:
  except:
    - gh-pages

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_sucess:
  - npm run gh-pages-travis
env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="dist"
    - TARGET_BRANCH="gh-pages"
    - GIT_NAME="travis"
    - GIT_EMAIL="deploy@travis-ci.org"


