#.travis.yml

language: node_js
node_js:
  - "6.10.2"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - ng build --prod --base-href "https://notsaltydev.github.io/todo-app/" ngh
  - angular-cli-ghpages

notifications:
  email:
    on_failure: change
    on_success: change
